In [19]:
import pandas as pd,numpy as np

In [20]:
# Importing the csv File
df=pd.read_csv('customer_shopping_behavior.csv')

In [51]:
df.head()

,customer_id,age,gender,item_purchased,category,purchase_amount_usd,location,size,color,season,...,subscription_status,shipping_type,discount_applied,promo_code_used,previous_purchases,payment_method,frequency_of_purchases,age_group,purchases_frequency,purchase_date
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,...,Yes,Express,Yes,Yes,14,Venmo,Fortnightly,Middle-age,14,2025-02-11
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,...,Yes,Express,Yes,Yes,2,Cash,Fortnightly,Young,14,2025-02-06
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,...,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly,Middle-age,7,2025-01-24
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,...,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly,Young,7,2025-01-29
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,...,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually,Middle-age,365,2026-01-11

In [55]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_usd', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases', 'age_group',
       'purchases_frequency'],
      dtype='str')

In [23]:
df.shape

(3900, 18)

In [ ]:
df.info()

In [ ]:
# converted to snake casing
df.columns=(df.columns.str.replace(" ","_")).str.lower()

In [ ]:
# removed the ( )
df=df.rename(columns={'purchase_amount_(usd)':'purchase_amount_usd'})

In [ ]:
df[['age','age_group']].head()

   age   age_group
0   55  Middle-age
1   19       Young
2   50  Middle-age
3   21       Young
4   45  Middle-age

In [ ]:
# created a new colum for age group
if_else_conditions = [
    (df["age"] >= 30) & (df["age"] < 40),  # 30 to 39
    (df["age"] >= 40) & (df["age"] < 60),  # 40 to 59
    (df["age"] >= 60),  # 60 and above
]
if_else_labels = [ "Adults", "Middle-age", "Senior"]

df["age_group"] = np.select(
    if_else_conditions, if_else_labels, default='Young'
)

In [ ]:
# craeted a new colum that showed the purchse frequency dates
freq_map={
    'Fortnightly':14,
    'Weekly':7,
    'Annually':365,
    'Quarterly':90,
    'Bi-Weekly':14,
    'Monthly': 30,
    'Every 3 Months':90
}
df['purchases_frequency']=df['frequency_of_purchases'].map(freq_map)

In [38]:
df['frequency_of_purchases'].unique()

<StringArray>
[   'Fortnightly',         'Weekly',       'Annually',      'Quarterly',
      'Bi-Weekly',        'Monthly', 'Every 3 Months']
Length: 7, dtype: str

In [54]:
df=df.drop('purchase_date',axis=1)